/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentMethod = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const AdminSettings = IDL.Record({
  'withdrawalEnabled' : IDL.Bool,
  'dailyCapINR' : IDL.Nat,
  'dailyCapNPR' : IDL.Nat,
  'earningEnabled' : IDL.Bool,
  'taskRewardMax' : IDL.Nat,
  'taskRewardMin' : IDL.Nat,
  'rewardMultiplier' : IDL.Nat,
});
export const ProductPlan = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
});
export const Time = IDL.Int;
export const SupportTicket = IDL.Record({
  'status' : TicketStatus,
  'problemSummary' : IDL.Text,
  'adminReply' : IDL.Text,
  'userId' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'guestName' : IDL.Text,
  'guestEmail' : IDL.Text,
  'ticketId' : IDL.Nat,
  'adminRepliedAt' : IDL.Opt(Time),
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'task_reward' : IDL.Null,
  'deposit' : IDL.Null,
  'vip_purchase' : IDL.Null,
  'spin_reward' : IDL.Null,
  'withdrawal' : IDL.Null,
  'login_bonus' : IDL.Null,
  'referral_bonus' : IDL.Null,
  'purchase' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransactionStatus,
  'paymentMethod' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'notes' : IDL.Text,
  'txType' : TransactionType,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'lastLoginDate' : IDL.Int,
  'isFrozen' : IDL.Bool,
  'referralCode' : IDL.Text,
  'frozenReason' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'loginStreak' : IDL.Nat,
  'user' : IDL.Principal,
  'weeklyPoints' : IDL.Nat,
  'referralEarnings' : IDL.Nat,
  'referredBy' : IDL.Opt(IDL.Principal),
  'deviceId' : IDL.Opt(IDL.Text),
  'totalPoints' : IDL.Nat,
  'vipTier' : IDL.Opt(IDL.Text),
  'vipExpiry' : IDL.Opt(IDL.Int),
});
export const EarningRecord = IDL.Record({
  'dailyEarned' : IDL.Nat,
  'consecutiveLosses' : IDL.Nat,
  'streakDays' : IDL.Nat,
  'lastEarnDate' : IDL.Int,
  'vipTier' : IDL.Opt(IDL.Text),
  'lastTaskTime' : IDL.Int,
});
export const FraudLog = IDL.Record({
  'action' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'reason' : IDL.Text,
});
export const BackupData = IDL.Record({
  'snapshotTime' : Time,
  'users' : IDL.Vec(UserProfile),
  'totalUsers' : IDL.Nat,
  'transactions' : IDL.Vec(Transaction),
  'totalBalance' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'user' : IDL.Principal,
  'weeklyPoints' : IDL.Nat,
  'vipTier' : IDL.Opt(IDL.Text),
});
export const VIPStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VIPPurchase = IDL.Record({
  'id' : IDL.Nat,
  'status' : VIPStatus,
  'userName' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'userEmail' : IDL.Text,
  'tier' : IDL.Text,
  'user' : IDL.Principal,
  'submittedAt' : IDL.Int,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
  'screenshot' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const SpinHistory = IDL.Record({
  'totalWon' : IDL.Nat,
  'totalSpins' : IDL.Nat,
  'lastSpin' : IDL.Int,
});
export const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });

export const idlService = IDL.Service({
  'addPaymentMethod' : IDL.Func([PaymentMethod], [], []),
  'approveTransaction' : IDL.Func([IDL.Nat], [], []),
  'approveVIPPurchase' : IDL.Func([IDL.Nat], [], []),
  'assignAdmin' : IDL.Func([], [IDL.Bool], []),
  'createDepositRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createSupportTicket' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'freezeUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
  'getAllPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'getAllProductPlans' : IDL.Func([], [IDL.Vec(ProductPlan)], ['query']),
  'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getEarningRecord' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EarningRecord)],
      ['query'],
    ),
  'getFraudLogs' : IDL.Func([], [IDL.Vec(FraudLog)], ['query']),
  'getFullBackupData' : IDL.Func([], [BackupData], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
  'getMyVIPPurchases' : IDL.Func([], [IDL.Vec(VIPPurchase)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPlatformRevenue' : IDL.Func(
      [],
      [
        IDL.Record({
          'revenue' : IDL.Nat,
          'canWithdraw' : IDL.Bool,
          'payouts' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPlatformStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalUsers' : IDL.Nat, 'totalTransactions' : IDL.Nat })],
      ['query'],
    ),
  'getSpinHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SpinHistory)],
      ['query'],
    ),
  'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVIPPurchases' : IDL.Func([], [IDL.Vec(VIPPurchase)], ['query']),
  'isUserFrozen' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isWithdrawalAllowed' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'processPurchase' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [IDL.Nat], []),
  'recordFraudLog' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'recordSpinResult' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [UserProfile], []),
  'rejectTransaction' : IDL.Func([IDL.Nat], [], []),
  'rejectVIPPurchase' : IDL.Func([IDL.Nat], [], []),
  'removePaymentMethod' : IDL.Func([IDL.Text], [], []),
  'replyToTicket' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'resolveTicket' : IDL.Func([IDL.Nat], [], []),
  'restoreUserBalances' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendAdminNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'submitVIPPurchase' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'unfreezeUser' : IDL.Func([IDL.Principal], [], []),
  'updateAdminSettings' : IDL.Func([AdminSettings], [], []),
  'updateDailyEarning' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'updatePlatformRevenue' : IDL.Func([IDL.Nat], [], []),
  'updateUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentMethod = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const AdminSettings = IDL.Record({
    'withdrawalEnabled' : IDL.Bool,
    'dailyCapINR' : IDL.Nat,
    'dailyCapNPR' : IDL.Nat,
    'earningEnabled' : IDL.Bool,
    'taskRewardMax' : IDL.Nat,
    'taskRewardMin' : IDL.Nat,
    'rewardMultiplier' : IDL.Nat,
  });
  const ProductPlan = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
  });
  const Time = IDL.Int;
  const SupportTicket = IDL.Record({
    'status' : TicketStatus,
    'problemSummary' : IDL.Text,
    'adminReply' : IDL.Text,
    'userId' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'guestName' : IDL.Text,
    'guestEmail' : IDL.Text,
    'ticketId' : IDL.Nat,
    'adminRepliedAt' : IDL.Opt(Time),
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'task_reward' : IDL.Null,
    'deposit' : IDL.Null,
    'vip_purchase' : IDL.Null,
    'spin_reward' : IDL.Null,
    'withdrawal' : IDL.Null,
    'login_bonus' : IDL.Null,
    'referral_bonus' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransactionStatus,
    'paymentMethod' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'notes' : IDL.Text,
    'txType' : TransactionType,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'lastLoginDate' : IDL.Int,
    'isFrozen' : IDL.Bool,
    'referralCode' : IDL.Text,
    'frozenReason' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'loginStreak' : IDL.Nat,
    'user' : IDL.Principal,
    'weeklyPoints' : IDL.Nat,
    'referralEarnings' : IDL.Nat,
    'referredBy' : IDL.Opt(IDL.Principal),
    'deviceId' : IDL.Opt(IDL.Text),
    'totalPoints' : IDL.Nat,
    'vipTier' : IDL.Opt(IDL.Text),
    'vipExpiry' : IDL.Opt(IDL.Int),
  });
  const EarningRecord = IDL.Record({
    'dailyEarned' : IDL.Nat,
    'consecutiveLosses' : IDL.Nat,
    'streakDays' : IDL.Nat,
    'lastEarnDate' : IDL.Int,
    'vipTier' : IDL.Opt(IDL.Text),
    'lastTaskTime' : IDL.Int,
  });
  const FraudLog = IDL.Record({
    'action' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'reason' : IDL.Text,
  });
  const BackupData = IDL.Record({
    'snapshotTime' : Time,
    'users' : IDL.Vec(UserProfile),
    'totalUsers' : IDL.Nat,
    'transactions' : IDL.Vec(Transaction),
    'totalBalance' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'user' : IDL.Principal,
    'weeklyPoints' : IDL.Nat,
    'vipTier' : IDL.Opt(IDL.Text),
  });
  const VIPStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VIPPurchase = IDL.Record({
    'id' : IDL.Nat,
    'status' : VIPStatus,
    'userName' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'userEmail' : IDL.Text,
    'tier' : IDL.Text,
    'user' : IDL.Principal,
    'submittedAt' : IDL.Int,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
    'screenshot' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const SpinHistory = IDL.Record({
    'totalWon' : IDL.Nat,
    'totalSpins' : IDL.Nat,
    'lastSpin' : IDL.Int,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  
  return IDL.Service({
    'addPaymentMethod' : IDL.Func([PaymentMethod], [], []),
    'approveTransaction' : IDL.Func([IDL.Nat], [], []),
    'approveVIPPurchase' : IDL.Func([IDL.Nat], [], []),
    'assignAdmin' : IDL.Func([], [IDL.Bool], []),
    'createDepositRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createSupportTicket' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'freezeUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'getAdminSettings' : IDL.Func([], [AdminSettings], ['query']),
    'getAllPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'getAllProductPlans' : IDL.Func([], [IDL.Vec(ProductPlan)], ['query']),
    'getAllSupportTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getEarningRecord' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EarningRecord)],
        ['query'],
      ),
    'getFraudLogs' : IDL.Func([], [IDL.Vec(FraudLog)], ['query']),
    'getFullBackupData' : IDL.Func([], [BackupData], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyTickets' : IDL.Func([], [IDL.Vec(SupportTicket)], ['query']),
    'getMyVIPPurchases' : IDL.Func([], [IDL.Vec(VIPPurchase)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPlatformRevenue' : IDL.Func(
        [],
        [
          IDL.Record({
            'revenue' : IDL.Nat,
            'canWithdraw' : IDL.Bool,
            'payouts' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalUsers' : IDL.Nat, 'totalTransactions' : IDL.Nat })],
        ['query'],
      ),
    'getSpinHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SpinHistory)],
        ['query'],
      ),
    'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVIPPurchases' : IDL.Func([], [IDL.Vec(VIPPurchase)], ['query']),
    'isUserFrozen' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isWithdrawalAllowed' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'processPurchase' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [IDL.Nat], []),
    'recordFraudLog' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'recordSpinResult' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [UserProfile], []),
    'rejectTransaction' : IDL.Func([IDL.Nat], [], []),
    'rejectVIPPurchase' : IDL.Func([IDL.Nat], [], []),
    'removePaymentMethod' : IDL.Func([IDL.Text], [], []),
    'replyToTicket' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'requestWithdrawal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'resolveTicket' : IDL.Func([IDL.Nat], [], []),
    'restoreUserBalances' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendAdminNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'submitVIPPurchase' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'unfreezeUser' : IDL.Func([IDL.Principal], [], []),
    'updateAdminSettings' : IDL.Func([AdminSettings], [], []),
    'updateDailyEarning' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updatePlatformRevenue' : IDL.Func([IDL.Nat], [], []),
    'updateUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };